# This compose allows to build the whole project in a "production"-like environment 
services:
  server:
    build:
      context: ./server
    expose:
      - 4000
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- localhost:4000"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - server_data:/app/data
  db:
    image: postgres:alpine3.14
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
  server_data:
