services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      db:
       condition: service_healthy
    volumes:
      - ./server/src:/app/src
      - ./server/prisma:/app/prisma
      - ./server/test:/app/test
      - ./server/package.json:/app/package.json
      - ./server/tsconfig.json:/app/tsconfig.json
      - ./server/tsconfig.build.json:/app/tsconfig.build.json
      - ./server/yarn.lock:/app/yarn.lock
    env_file:
      - .env
  db:
    image: postgres:alpine3.16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
