name:                ToysRevive-server
version:             0.1.0.0
github:              "0Nom4D/ToysRevive"
license:             BSD-3-Clause
author:              "Arthur Jamet"
maintainer:          "arthur.jamet@gmail.com"
copyright:           "2023 Arthur Jamet"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/0Nom4D/ToysRevive#readme>

dependencies:
- base >= 4.7 && < 5
- servant

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  ToysRevive-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ToysRevive-server

tests:
  ToysRevive-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ToysRevive-server
