package nom4d.toysrevive.ui.theme

import androidx.compose.ui.graphics.Color

val mdThemeLightPrimary = Color(0xFF006590)
val mdThemeLightOnPrimary = Color(0xFFFFFFFF)
val mdThemeLightPrimaryContainer = Color(0xFFC8E6FF)
val mdThemeLightOnPrimaryContainer = Color(0xFF001E2E)
val mdThemeLightSecondary = Color(0xFF4F606E)
val mdThemeLightOnSecondary = Color(0xFFFFFFFF)
val mdThemeLightSecondaryContainer = Color(0xFFD2E5F5)
val mdThemeLightOnSecondaryContainer = Color(0xFF0B1D29)
val mdThemeLightTertiary = Color(0xFF984700)
val mdThemeLightOnTertiary = Color(0xFFFFFFFF)
val mdThemeLightTertiaryContainer = Color(0xFFFFDBC8)
val mdThemeLightOnTertiaryContainer = Color(0xFF321300)
val mdThemeLightError = Color(0xFFBA1A1A)
val mdThemeLightErrorContainer = Color(0xFFFFDAD6)
val mdThemeLightOnError = Color(0xFFFFFFFF)
val mdThemeLightOnErrorContainer = Color(0xFF410002)
val mdThemeLightBackground = Color(0xFFF8FDFF)
val mdThemeLightOnBackground = Color(0xFF001F25)
val mdThemeLightSurface = Color(0xFFF8FDFF)
val mdThemeLightOnSurface = Color(0xFF001F25)
val mdThemeLightSurfaceVariant = Color(0xFFDDE3EA)
val mdThemeLightOnSurfaceVariant = Color(0xFF41484D)
val mdThemeLightOutline = Color(0xFF71787E)
val mdThemeLightInverseOnSurface = Color(0xFFD6F6FF)
val mdThemeLightInverseSurface = Color(0xFF00363F)
val mdThemeLightInversePrimary = Color(0xFF87CEFF)
val mdThemeLightShadow = Color(0xFF000000)
val mdThemeLightSurfaceTint = Color(0xFF006590)
val mdThemeLightOutlineVariant = Color(0xFFC1C7CE)
val mdThemeLightScrim = Color(0xFF000000)

val mdThemeDarkPrimary = Color(0xFF87CEFF)
val mdThemeDarkOnPrimary = Color(0xFF00344D)
val mdThemeDarkPrimaryContainer = Color(0xFF004C6D)
val mdThemeDarkOnPrimaryContainer = Color(0xFFC8E6FF)
val mdThemeDarkSecondary = Color(0xFFB7C9D8)
val mdThemeDarkOnSecondary = Color(0xFF21323E)
val mdThemeDarkSecondaryContainer = Color(0xFF384956)
val mdThemeDarkOnSecondaryContainer = Color(0xFFD2E5F5)
val mdThemeDarkTertiary = Color(0xFFFFB68A)
val mdThemeDarkOnTertiary = Color(0xFF522300)
val mdThemeDarkTertiaryContainer = Color(0xFF743500)
val mdThemeDarkOnTertiaryContainer = Color(0xFFFFDBC8)
val mdThemeDarkError = Color(0xFFFFB4AB)
val mdThemeDarkErrorContainer = Color(0xFF93000A)
val mdThemeDarkOnError = Color(0xFF690005)
val mdThemeDarkOnErrorContainer = Color(0xFFFFDAD6)
val mdThemeDarkBackground = Color(0xFF001F25)
val mdThemeDarkOnBackground = Color(0xFFA6EEFF)
val mdThemeDarkSurface = Color(0xFF001F25)
val mdThemeDarkOnSurface = Color(0xFFA6EEFF)
val mdThemeDarkSurfaceVariant = Color(0xFF41484D)
val mdThemeDarkOnSurfaceVariant = Color(0xFFC1C7CE)
val mdThemeDarkOutline = Color(0xFF8B9198)
val mdThemeDarkInverseOnSurface = Color(0xFF001F25)
val mdThemeDarkInverseSurface = Color(0xFFA6EEFF)
val mdThemeDarkInversePrimary = Color(0xFF006590)
val mdThemeDarkShadow = Color(0xFF000000)
val mdThemeDarkSurfaceTint = Color(0xFF87CEFF)
val mdThemeDarkOutlineVariant = Color(0xFF41484D)
val mdThemeDarkScrim = Color(0xFF000000)

val seed = Color(0xFF00AAEF)
