name: Kotlin Jetpack Compose

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/jetpack_compose.yaml
      - '**/detekt.yml'
      - '**/main/java/nom4d/**/*.kt'
      - '**.kts'

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Install Ktlint"
        uses: nbadal/action-ktlint-setup@v1

      - name: "Launching Ktlint"
        working-directory: mobile
        run: ktlint
  Build:
    runs-on: ubuntu-latest
    needs: [ Lint ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current

      - name: Build debug
        working-directory: mobile
        run: ./gradlew assembleDebug --stacktrace

      - name: Build release
        working-directory: mobile
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs
          path: mobile/app/build/outputs
  Test:
    runs-on: ubuntu-latest
    needs: [ Lint ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current

      - name: Run local tests
        working-directory: mobile
        run: ./gradlew test --stacktrace

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: mobile/app/build/reports
  Detekt:
    runs-on: ubuntu-latest
    needs: [ Lint, Build ]
    steps:
      - name: Download detekt
        working-directory: mobile
        run: |
          curl -sSLO https://github.com/detekt/detekt/releases/download/v1.23.4/detekt-cli-1.23.4.zip
          unzip detekt-cli-1.23.4.zip
          ./detekt-cli-1.23.4/bin/detekt-cli --help
      - name: Launch detekt
        working-directory: mobile
        run: ./detekt-cli-1.23.4/bin/detekt-cli --config ./detekt.yml -r xml:app/build/reports/analysis.xml
      - name: Upload analysis reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: static_analysis
          path: mobile/app/build/reports/analysis.xml
