name: Kotlin Linter

on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - .github/workflows/jetpack_compose.yaml
      - .github/workflows/ktlint.yaml
      - '**/main/java/nom4d/**/*.kt'
      - '**.kts'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Install Ktlint"
        uses: nbadal/action-ktlint-setup@v1

      - name: "Launching Ktlint"
        working-directory: mobile
        run: ktlint
