name: Server
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/server.yaml
      - 'server/**'

defaults:
  run:
    shell: bash
    container: node:18-alpine
    working-directory: ./server

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install test dependencies
        run: yarn install
      - name: Build
        run: yarn build
  Lint:
    runs-on: ubuntu-latest
    needs: [ Build ]
    steps:
      - uses: actions/checkout@v4
      - name: Run Linter
        run: yarn lint
  Prettier:
    runs-on: ubuntu-latest
    needs: [ Build ]
    steps:
      - uses: actions/checkout@v4
      - name: Run Linter
        run: yarn format
  Tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [ Build ]
    steps:
      - uses: actions/checkout@v4
      #TODO
