name: Server's Workflow
on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - .github/workflows/server.yaml
      - 'server/**'

defaults:
  run:
    working-directory: ./server

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ./.github/actions/install-stack
      - uses: ./.github/actions/cache
      - name: Compile Project
        run: stack build
  Lint:
    runs-on: ubuntu-20.04
    needs: [ Build ]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ./.github/actions/cache
      # TODO: DO WE REALLY NEED TO DL Stack?- uses: ./.github/actions/install-stack
      - name: Setup HLint
        run: stack install hlint
      - name: Run HLint
        run: hlint src app
  UTests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    needs: [ Build ]
    steps:
      - uses: actions/checkout@v2.3.4
      # TODO: DO WE REALLY NEED TO DL Stack?- uses: ./.github/actions/install-stack
      - uses: ./.github/actions/cache
      - name: Install Coverage utility
        run: stack install hpc-codecov
      - name: Run unit tests
        run: stack test --coverage
      # TODO: Report Coverage
  # RTests:
  #   name: Robot Tests
  #   runs-on: ubuntu-20.04
  #   needs: [ Build ]
  #   steps:
  #     - uses: actions/checkout@v2.3.4
  #     - uses: ./.github/actions/install-stack
  #     - uses: ./.github/actions/cache
  #     - name: Build the server 
  #       run: stack run &
